{
 "title": "Host Performance (v0.1) (PainNet Dev)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  usage_user AS \"usage_user\",\n  usage_system AS \"usage_system\",\n  usage_iowait AS \"usage_iowait\",\n  usage_irq AS \"usage_irq\",\n  usage_softirq AS \"usage_softirq\",\n  usage_nice AS \"usage_nice\",\n  usage_guest AS \"usage_guest\",\n  usage_guest_nice AS \"usage_guest_nice\",\n  usage_steal AS \"usage_steal\"\nFROM cpu\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  uptime\nFROM system\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "% Disk Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  used_percent AS \"% Used\"\nFROM disk\nWHERE\n  $__timeFilter(\"time\") AND\n  path = '/'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Process Handling",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  (CASE WHEN sum(interrupts) >= lag(sum(interrupts)) OVER (ORDER BY $__timeGroup(\"time\",$__interval)) THEN sum(interrupts) - lag(sum(interrupts)) OVER (ORDER BY $__timeGroup(\"time\",$__interval)) WHEN lag(sum(interrupts)) OVER (ORDER BY $__timeGroup(\"time\",$__interval)) IS NULL THEN NULL ELSE sum(interrupts) END) AS \"interrupts\",\n  (CASE WHEN sum(processes_forked) >= lag(sum(processes_forked)) OVER (ORDER BY $__timeGroup(\"time\",$__interval)) THEN sum(processes_forked) - lag(sum(processes_forked)) OVER (ORDER BY $__timeGroup(\"time\",$__interval)) WHEN lag(sum(processes_forked)) OVER (ORDER BY $__timeGroup(\"time\",$__interval)) IS NULL THEN NULL ELSE sum(processes_forked) END) AS \"processes_forked\",\n  (CASE WHEN sum(context_switches) >= lag(sum(context_switches)) OVER (ORDER BY $__timeGroup(\"time\",$__interval)) THEN sum(context_switches) - lag(sum(context_switches)) OVER (ORDER BY $__timeGroup(\"time\",$__interval)) WHEN lag(sum(context_switches)) OVER (ORDER BY $__timeGroup(\"time\",$__interval)) IS NULL THEN NULL ELSE sum(context_switches) END) AS \"context_switches\"\nFROM kernel\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  used,\n  buffered,\n  cached,\n  free\nFROM mem\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}