{
 "title": "Monitoring Icebox",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Network Sync Lag per Host",
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "with expected_heights as (\n\tselect\n\t\thost,\n\t\tpeer_ID,\n\t\tmax(gauge) as \"height\"\n\tfrom lotus_chain_node_height_expected\n\tgroup by 1, 2\n), actual_heights as (\n\tselect\n\t\thost,\n\t\tpeer_ID,\n\t\tmax(gauge) as \"height\"\n\tfrom lotus_chain_node_height\n\tgroup by 1, 2\n)\nselect\n\ta.host as \"Hostname\",\n\ta.peer_ID as \"PeerID\",\n\ta.height as \"Node Sync Height\",\n\te.height - a.height as \"Sync Lag\"\nfrom actual_heights a JOIN expected_heights e USING (host, peer_ID)\n;"
    }
   ]
  },
  {
   "title": "Top 100 Trends of Consecutive Null Rounds",
   "type": "table",
   "description": "All heights where a series of null rounds were concluded and the height at which they concluded.",
   "gridPos": { "h": 17, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH distinct_heights AS (\n\tSELECT DISTINCT\n\t\theight::int AS height\n\tFROM\n\t\tblock_headers\n\tORDER BY\n\t\theight::int DESC\n),\nheight_diffs AS (\n\tSELECT\n\t\theight,\n\t\theight - lag(height) OVER (ORDER BY height) - 1 AS \"consecutive_null_rounds\"\n\tFROM\n\t\tdistinct_heights ORDER BY\n\t\t\theight DESC\n)\nSELECT\n\theight as \"Height\",\n\tconsecutive_null_rounds as \"Consecutive Null Rounds\"\nFROM\n\theight_diffs\nWHERE\n\tconsecutive_null_rounds > 0\nORDER BY 2 DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Deal Terminations",
   "type": "graph",
   "description": "Duration reported by lotus between receipt and validation of a block.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "with epoch as (\n    select height,\n           time_bucket('30s', to_timestamp(block_headers.timestamp)) as \"time\",\n           parent_state_root\n    from block_headers\n    where to_timestamp(timestamp) > date $__timeFrom() - interval '3 hour'\n     and to_timestamp(timestamp) < $__timeTo()\n    group by timestamp, height, parent_state_root, parent_weight\n    order by height desc, parent_weight desc\n),\n     deal_terminations_per_height as (\n         select epoch.time,\n                sum(count(mdp.deal_id) filter (where slash_epoch > 0 and slash_epoch is not null)) over (order by epoch.time rows between 360 preceding and current row) as \"terminated\",\n                sum(count(mdp.deal_id)) over (order by epoch.time rows between 360 preceding and current row) as \"total\"\n         from epoch\n                  left join market_deal_states mds on epoch.parent_state_root = mds.state_root\n                  left join market_deal_proposals mdp on mds.deal_id = mdp.deal_id\n         group by epoch.time\n         order by epoch.time desc\n     )\nselect distinct on (time) time,\n                          total,\n                          (case when total = '0' then 0 else terminated/total end) as \"percent\"\nfrom deal_terminations_per_height\nwhere time > $__timeFrom()\n  and time < $__timeTo()\norder by time desc"
    }
   ]
  }
 ]
}