{
 "title": "Sentinel (v0.1) (PainNet Dev)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "# Chain State" },
  {
   "title": "Reported Blocks",
   "type": "graph",
   "description": "Number of blocks reported by network by Miner ID.",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "blocks won" }
   ],
   "targets": [
    {
     "rawSql": "WITH \"elections\" AS (\n  SELECT\n    to_timestamp(\"timestamp\") AS \"time\",\n    miner AS \"miner\"\n  FROM \"blocks\"\n  WHERE\n    $__unixEpochFilter(\"timestamp\")\n)\nSELECT\n  $__timeGroupAlias(\"time\",$__interval,0),\n  miner AS \"metric\",\n  max(1) AS \"election\"\nFROM \"elections\"\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1, 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Time since Last Block",
   "type": "stat",
   "description": "Time elapsed since last block found.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\",\n  extract(epoch from NOW() - to_timestamp(\"timestamp\")) AS \"since_last_block\"\nFROM \"blocks\"\nORDER BY 2 ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Avg Message Size",
   "type": "graph",
   "description": "Average message size (within minimum/maximum band).",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  min(message_size) AS \"Minimum\",\n  avg(message_size) AS \"Average\",\n  max(message_size) AS \"Maximum\"\nFROM \"chain.messages\"\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  count(message_size) AS \"Count\"\nFROM \"chain.messages\"\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Messages per 30 minutes",
   "type": "graph",
   "description": "Total message size found per 30 minute interval.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  count(message_size) AS \"Total\"\nFROM \"chain.messages\"\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Message Size",
   "type": "graph",
   "description": "Total message size found on-chain.",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  sum(message_size) AS \"Total\"\nFROM \"chain.messages\"\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Block Header Size",
   "type": "graph",
   "description": "Size of block headers.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  avg(header_size) AS \"header_size\"\nFROM \"chain.block\"\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Actor Messages with Exitcode",
   "type": "graph",
   "description": "Number of actor messages executed grouped by exit code.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval, 0),\n  CONCAT(actor,'/',method,' -> ',exitcode) AS \"metric\",\n  sum(count) AS \"count\"\nFROM \"chain.actors\"\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1, 2\nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Block Header Delay",
   "type": "graph",
   "description": "Time between block header arrival and the epoch time expected for the tipset of that block.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (recorded_at - header_timestamp) AS \"Delay\"\nFROM \"chain.block\"\nWHERE\n  $__timeFilter(\"time\") AND (recorded_at - header_timestamp) < 50000000000\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Block-to-Tipset Ratio",
   "type": "stat",
   "description": "Lifetime Total blocks per Tipset",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\",\n  count(cid)::float/max(height)::float AS \"block_tipset_ratio\"\nFROM \"blocks\""
    }
   ]
  },
  {
   "title": "Total Tipsets",
   "type": "stat",
   "description": "Total Tipsets on Chain",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\",\n  max(height) AS \"total_tipsets\"\nFROM \"blocks\""
    }
   ]
  },
  {
   "title": "Total Blocks",
   "type": "stat",
   "description": "Total Blocks on Chain",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\",\n  count(*) AS \"total_blocks\"\nFROM \"blocks\""
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 }, "content": "# Lotus Daemon" },
  {
   "title": "Messages Recieved",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  counter - lag(counter) OVER (ORDER BY \"time\") AS \"Success\"\nFROM lotus_message_success\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  counter - lag(counter) OVER (ORDER BY \"time\") AS \"Failure\"\nFROM lotus_message_failure\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Connected Peers Count",
   "type": "graph",
   "description": "Number of peers connected to the lotus node.",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  gauge\nFROM lotus_peer_count\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Block Validation Time",
   "type": "graph",
   "description": "Duration reported by lotus between receipt and validation of a block.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  gauge AS \"Validation Duration\"\nFROM lotus_block_validation_ms\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  avg(gauge) OVER (ORDER BY \"time\" ROWS 20 PRECEDING) AS \"Average Duration\"\nFROM lotus_block_validation_ms\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}