{
 "title": "Mpool Stats",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Wait Time Histogram",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select \nraw.time, raw.\"10\" as \"0\",\nraw.\"30\" - raw.\"10\" as \"10\",\nraw.\"60\" - raw.\"30\" as \"30\",\nraw.\"120\" - raw.\"60\" as \"60\",\nraw.\"240\" - raw.\"120\" as \"120\",\nraw.\"600\" - raw.\"240\" as \"240\",\nraw.\"1800\" - raw.\"600\" as \"600\",\nraw.\"3600\" - raw.\"1800\" as \"1800\",\nraw.\"count\" - raw.\"3600\" as \"3600\"\nFROM (SELECT\n  \"time\" AS \"time\",\n  (CASE WHEN \"10\" >= lag(\"10\") OVER (ORDER BY \"time\") THEN \"10\" - lag(\"10\") OVER (ORDER BY \"time\") WHEN lag(\"10\") OVER (ORDER BY \"time\") IS NULL THEN NULL ELSE \"10\" END) AS \"10\",\n  (CASE WHEN \"30\" >= lag(\"30\") OVER (ORDER BY \"time\") THEN \"30\" - lag(\"30\") OVER (ORDER BY \"time\") WHEN lag(\"30\") OVER (ORDER BY \"time\") IS NULL THEN NULL ELSE \"30\" END) AS \"30\",\n  (CASE WHEN \"60\" >= lag(\"60\") OVER (ORDER BY \"time\") THEN \"60\" - lag(\"60\") OVER (ORDER BY \"time\") WHEN lag(\"60\") OVER (ORDER BY \"time\") IS NULL THEN NULL ELSE \"60\" END) AS \"60\",\n  (CASE WHEN \"120\" >= lag(\"120\") OVER (ORDER BY \"time\") THEN \"120\" - lag(\"120\") OVER (ORDER BY \"time\") WHEN lag(\"120\") OVER (ORDER BY \"time\") IS NULL THEN NULL ELSE \"120\" END) AS \"120\",\n  (CASE WHEN \"240\" >= lag(\"240\") OVER (ORDER BY \"time\") THEN \"240\" - lag(\"240\") OVER (ORDER BY \"time\") WHEN lag(\"240\") OVER (ORDER BY \"time\") IS NULL THEN NULL ELSE \"240\" END) AS \"240\",\n  (CASE WHEN \"600\" >= lag(\"600\") OVER (ORDER BY \"time\") THEN \"600\" - lag(\"600\") OVER (ORDER BY \"time\") WHEN lag(\"600\") OVER (ORDER BY \"time\") IS NULL THEN NULL ELSE \"600\" END) AS \"600\",\n  (CASE WHEN \"1800\" >= lag(\"1800\") OVER (ORDER BY \"time\") THEN \"1800\" - lag(\"1800\") OVER (ORDER BY \"time\") WHEN lag(\"1800\") OVER (ORDER BY \"time\") IS NULL THEN NULL ELSE \"1800\" END) AS \"1800\",\n  (CASE WHEN \"3600\" >= lag(\"3600\") OVER (ORDER BY \"time\") THEN \"3600\" - lag(\"3600\") OVER (ORDER BY \"time\") WHEN lag(\"3600\") OVER (ORDER BY \"time\") IS NULL THEN NULL ELSE \"3600\" END) AS \"3600\",\n  (CASE WHEN \"count\" >= lag(\"count\") OVER (ORDER BY \"time\") THEN \"count\" - lag(\"count\") OVER (ORDER BY \"time\") WHEN lag(\"count\") OVER (ORDER BY \"time\") IS NULL THEN NULL ELSE \"count\" END) AS \"count\"\nFROM lotusmpool_msg_wait\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1\n) as raw"
    }
   ]
  },
  {
   "title": "Inbound Messages Rate since Last Measure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Window PoSt Msgs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (CASE\n   WHEN counter >= lag(counter) OVER (ORDER BY \"time\") THEN counter - lag(counter) OVER (ORDER BY \"time\")\n   WHEN lag(counter) OVER (ORDER BY \"time\") IS NULL THEN NULL\n   ELSE counter \n  END) / extract(epoch from \"time\" - lag(\"time\") OVER (ORDER BY \"time\")) AS \"Other\"\nFROM lotusmpool_msg_inbound\nWHERE\n  $__timeFilter(\"time\") AND\n  msg_type != 'wpost'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (CASE\n   WHEN counter >= lag(counter) OVER (ORDER BY \"time\") THEN counter - lag(counter) OVER (ORDER BY \"time\")\n   WHEN lag(counter) OVER (ORDER BY \"time\") IS NULL THEN NULL\n   ELSE counter \n  END) / extract(epoch from \"time\" - lag(\"time\") OVER (ORDER BY \"time\")) AS \"Window PoSt\"\nFROM lotusmpool_msg_inbound\nWHERE\n  $__timeFilter(\"time\") AND\n  msg_type = 'wpost'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Mpool Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  gauge\nFROM lotusmpool_mpool_size\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Mpool Age",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  quantile AS metric,\n  gauge\nFROM lotusmpool_mpool_age\nWHERE\n  $__timeFilter(\"time\")\nORDER BY \"time\", \"metric\""
    }
   ]
  },
  {
   "title": "Mpool Wait Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  count - lag(count) OVER (ORDER BY \"time\") AS \"count\",\n  sum\nFROM lotusmpool_msg_wait\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}