{
 "title": "Sentinel Stats",
 "time": { "from": "2020-10-05T01:28:03.884Z", "to": "2020-10-05T01:42:54.070Z" },
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Tasks Processed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(\"completed_at\", '1s', 0) as \"time\",\n  count(*) as \"Tipsets\"\nfrom visor_processing_statechanges\nwhere completed_at is not null and $__timeFilter(\"completed_at\")\ngroup by 1 \norder by 1"
    },
    {
     "rawSql": "select\n  time_bucket('1s', \"completed_at\") as \"time\",\n  count(*) as \"Messages\"\nfrom visor_processing_messages\nwhere completed_at is not null and $__timeFilter(\"completed_at\")\ngroup by 1 \norder by 1"
    },
    {
     "rawSql": "select\n  time_bucket('1s', \"completed_at\") as \"time\",\n  count(*) as \"Actor States\"\nfrom visor_processing_actors\nwhere completed_at is not null and $__timeFilter(\"completed_at\")\ngroup by 1 \norder by 1"
    }
   ]
  },
  {
   "title": "Largest Node Sync Lag",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with expected_heights as (\n\tselect\n\t\thost,\n\t\tpeer_ID,\n\t\tmax(gauge) as \"height\"\n\tfrom lotus_chain_node_height_expected\n\tgroup by 1, 2\n), actual_heights as (\n\tselect\n\t\thost,\n\t\tpeer_ID,\n\t\tmax(gauge) as \"height\"\n\tfrom lotus_chain_node_height\n\tgroup by 1, 2\n)\nselect\n\tnow() as \"time\",\n\tmax(e.height - a.height) as \"Sync Lag\"\nfrom actual_heights a JOIN expected_heights e USING (host, peer_ID)\ngroup by 1\n;"
    }
   ]
  },
  {
   "title": "Alerts That Aren't OK",
   "type": "alertlist",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  counter\nFROM lotus_pubsub_recv_rpc\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Expected Chain Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 18, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() as \"time\", ((EXTRACT(EPOCH FROM now())::INTEGER - block_headers.timestamp) / 30)::INTEGER as \"Expected Height\" FROM block_headers WHERE block_headers.height = 0 LIMIT 1"
    }
   ]
  },
  {
   "title": "Network Sync Lag per Host",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "with expected_heights as (\n\tselect\n\t\thost,\n\t\tpeer_ID,\n\t\tmax(gauge) as \"height\"\n\tfrom lotus_chain_node_height_expected\n\tgroup by 1, 2\n), actual_heights as (\n\tselect\n\t\thost,\n\t\tpeer_ID,\n\t\tmax(gauge) as \"height\"\n\tfrom lotus_chain_node_height\n\tgroup by 1, 2\n)\nselect\n\ta.host as \"Hostname\",\n\ta.peer_ID as \"PeerID\",\n\ta.height as \"Node Sync Height\",\n\te.height - a.height as \"Sync Lag\"\nfrom actual_heights a JOIN expected_heights e USING (host, peer_ID)\n;"
    }
   ]
  }
 ]
}