{
 "title": "Top Miners by Block Reward",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Top Miners Processed At",
   "type": "table",
   "description": "The height of the chain when the current ranking was produced.",
   "gridPos": { "h": 3, "w": 5, "x": 2, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  current_timestamp,\n  current_height\nFROM top_miners_by_base_reward_max_height\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Updated At",
   "type": "stat",
   "description": "The Epoch Miner Ranks was last update at.",
   "gridPos": { "h": 3, "w": 5, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n NOW() as time,\n *\nFROM\n  top_miners_by_base_reward_max_height\n\n"
    }
   ]
  },
  {
   "title": "Top Miners by Block Reward",
   "type": "table-old",
   "description": "All accumulated rewards for miners updated each day at midnight.",
   "gridPos": { "h": 25, "w": 11, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  rank AS \"Rank\",\n  miner AS \"Miner\",\n  total_reward/(10^18) AS \"Total Reward\"\nFROM top_miners_by_base_reward\nORDER BY 1 ASC"
    }
   ]
  }
 ]
}