{
 "title": "Sentinel Visor Progress",
 "time": { "from": "now-3h", "to": "now-1m" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DB", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Blocks Task",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select r.completed_at as \"time\",\n       r.height as height,\n       unix_to_height(extract(epoch from now() at time zone 'utc')::integer)-r.height as lag\nfrom visor_processing_reports r\nWHERE $__timeFilter(r.completed_at) and r.task='blocks' and r.reporter LIKE '%_eks%'\norder by r.completed_at"
    }
   ]
  },
  {
   "title": "Messages Task",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select r.completed_at as \"time\",\n       r.height as height,\n       unix_to_height(extract(epoch from now() at time zone 'utc')::integer)-r.height as lag\nfrom visor_processing_reports r\nWHERE $__timeFilter(r.completed_at) and r.task='messages' and r.reporter LIKE '%_eks%'\norder by r.completed_at"
    }
   ]
  },
  {
   "title": "Chain Economics Task",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select r.completed_at as \"time\",\n       r.height as height,\n       unix_to_height(extract(epoch from now() at time zone 'utc')::integer)-r.height as lag\nfrom visor_processing_reports r\nWHERE $__timeFilter(r.completed_at) and r.task='chaineconomics' and r.reporter LIKE '%_eks%'\norder by r.completed_at"
    }
   ]
  },
  {
   "title": "Actor States (raw) Task",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select r.completed_at as \"time\",\n       r.height as height,\n       unix_to_height(extract(epoch from now() at time zone 'utc')::integer)-r.height as lag\nfrom visor_processing_reports r\nWHERE $__timeFilter(r.completed_at) and r.task='actorstatesraw' and r.reporter LIKE '%_eks%'\norder by r.completed_at"
    }
   ]
  },
  {
   "title": "Head indexer height by task",
   "type": "graph",
   "description": "The number of tipset state changes left to process",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "TipSets" }
   ],
   "targets": [
    {
     "rawSql": "select\n       \n       r.completed_at as \"time\",\n       r.height as value,\n       r.task as task\nfrom visor_processing_reports r\nWHERE $__timeFilter(r.completed_at) AND r.reporter LIKE '%_eks%'\norder by r.completed_at"
    }
   ]
  },
  {
   "title": "Processing reports status",
   "type": "graph",
   "description": "May be one of OK, INFO or ERROR",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(completed_at,$__interval,0),\n  status AS metric,\n  count(height) AS \"height\"\nFROM visor_processing_reports\nWHERE\n  $__timeFilter(completed_at) AND\n  reporter LIKE '%_eks%'\nGROUP BY 1, status,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}