name: Build Dependencies

on:
  push:

jobs:
  build:
    name: Build Telegraf
    runs-on: ubuntu-latest

    steps:
    - name: Prepare go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    - name: Prepare build deps
      run: sudo apt update -q && sudo apt install -yq mesa-opencl-icd ocl-icd-opencl-dev
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Build binary
      run: make telegraf
    - name: Test telegraf sample config
      run: build/telegraf --sample-config > /dev/null

